spring.application.name=NovaSpend

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.cache.interceptor=TRACE

# JWT
jwt.secretKey=${JWT_SECRET_KEY}
jwt.accessTokenExpiry=900
jwt.refreshTokenExpiry=604800
